// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: app/reverse/command/command.proto

package command

import (
	reverse "github.com/xtls/xray-core/app/reverse"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplaceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *reverse.Config        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceConfigRequest) Reset() {
	*x = ReplaceConfigRequest{}
	mi := &file_app_reverse_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceConfigRequest) ProtoMessage() {}

func (x *ReplaceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceConfigRequest.ProtoReflect.Descriptor instead.
func (*ReplaceConfigRequest) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *ReplaceConfigRequest) GetConfig() *reverse.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ReplaceConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceConfigResponse) Reset() {
	*x = ReplaceConfigResponse{}
	mi := &file_app_reverse_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceConfigResponse) ProtoMessage() {}

func (x *ReplaceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceConfigResponse.ProtoReflect.Descriptor instead.
func (*ReplaceConfigResponse) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{1}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_reverse_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_reverse_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_reverse_command_command_proto_rawDescGZIP(), []int{2}
}

var File_app_reverse_command_command_proto protoreflect.FileDescriptor

const file_app_reverse_command_command_proto_rawDesc = "" +
	"\n" +
	"!app/reverse/command/command.proto\x12\x18xray.app.reverse.command\x1a\x18app/reverse/config.proto\"H\n" +
	"\x14ReplaceConfigRequest\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.xray.app.reverse.ConfigR\x06config\"\x17\n" +
	"\x15ReplaceConfigResponse\"\b\n" +
	"\x06Config2\x84\x01\n" +
	"\x0eReverseService\x12r\n" +
	"\rReplaceConfig\x12..xray.app.reverse.command.ReplaceConfigRequest\x1a/.xray.app.reverse.command.ReplaceConfigResponse\"\x00Bj\n" +
	"\x1ccom.xray.app.reverse.commandP\x01Z-github.com/xtls/xray-core/app/reverse/command\xaa\x02\x18Xray.App.Reverse.Commandb\x06proto3"

var (
	file_app_reverse_command_command_proto_rawDescOnce sync.Once
	file_app_reverse_command_command_proto_rawDescData []byte
)

func file_app_reverse_command_command_proto_rawDescGZIP() []byte {
	file_app_reverse_command_command_proto_rawDescOnce.Do(func() {
		file_app_reverse_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_reverse_command_command_proto_rawDesc), len(file_app_reverse_command_command_proto_rawDesc)))
	})
	return file_app_reverse_command_command_proto_rawDescData
}

var file_app_reverse_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_reverse_command_command_proto_goTypes = []any{
	(*ReplaceConfigRequest)(nil),  // 0: xray.app.reverse.command.ReplaceConfigRequest
	(*ReplaceConfigResponse)(nil), // 1: xray.app.reverse.command.ReplaceConfigResponse
	(*Config)(nil),                // 2: xray.app.reverse.command.Config
	(*reverse.Config)(nil),        // 3: xray.app.reverse.Config
}
var file_app_reverse_command_command_proto_depIdxs = []int32{
	3, // 0: xray.app.reverse.command.ReplaceConfigRequest.config:type_name -> xray.app.reverse.Config
	0, // 1: xray.app.reverse.command.ReverseService.ReplaceConfig:input_type -> xray.app.reverse.command.ReplaceConfigRequest
	1, // 2: xray.app.reverse.command.ReverseService.ReplaceConfig:output_type -> xray.app.reverse.command.ReplaceConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_reverse_command_command_proto_init() }
func file_app_reverse_command_command_proto_init() {
	if File_app_reverse_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_reverse_command_command_proto_rawDesc), len(file_app_reverse_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_reverse_command_command_proto_goTypes,
		DependencyIndexes: file_app_reverse_command_command_proto_depIdxs,
		MessageInfos:      file_app_reverse_command_command_proto_msgTypes,
	}.Build()
	File_app_reverse_command_command_proto = out.File
	file_app_reverse_command_command_proto_goTypes = nil
	file_app_reverse_command_command_proto_depIdxs = nil
}
