// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: app/ratelimit/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RateLimitService_SetUserRateLimit_FullMethodName    = "/xray.app.ratelimit.command.RateLimitService/SetUserRateLimit"
	RateLimitService_GetUserRateLimit_FullMethodName    = "/xray.app.ratelimit.command.RateLimitService/GetUserRateLimit"
	RateLimitService_RemoveUserRateLimit_FullMethodName = "/xray.app.ratelimit.command.RateLimitService/RemoveUserRateLimit"
	RateLimitService_GetUserSpeed_FullMethodName        = "/xray.app.ratelimit.command.RateLimitService/GetUserSpeed"
	RateLimitService_ListUserSpeeds_FullMethodName      = "/xray.app.ratelimit.command.RateLimitService/ListUserSpeeds"
)

// RateLimitServiceClient is the client API for RateLimitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimitServiceClient interface {
	SetUserRateLimit(ctx context.Context, in *SetUserRateLimitRequest, opts ...grpc.CallOption) (*SetUserRateLimitResponse, error)
	GetUserRateLimit(ctx context.Context, in *GetUserRateLimitRequest, opts ...grpc.CallOption) (*GetUserRateLimitResponse, error)
	RemoveUserRateLimit(ctx context.Context, in *RemoveUserRateLimitRequest, opts ...grpc.CallOption) (*RemoveUserRateLimitResponse, error)
	GetUserSpeed(ctx context.Context, in *GetUserSpeedRequest, opts ...grpc.CallOption) (*GetUserSpeedResponse, error)
	ListUserSpeeds(ctx context.Context, in *ListUserSpeedsRequest, opts ...grpc.CallOption) (*ListUserSpeedsResponse, error)
}

type rateLimitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimitServiceClient(cc grpc.ClientConnInterface) RateLimitServiceClient {
	return &rateLimitServiceClient{cc}
}

func (c *rateLimitServiceClient) SetUserRateLimit(ctx context.Context, in *SetUserRateLimitRequest, opts ...grpc.CallOption) (*SetUserRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserRateLimitResponse)
	err := c.cc.Invoke(ctx, RateLimitService_SetUserRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimitServiceClient) GetUserRateLimit(ctx context.Context, in *GetUserRateLimitRequest, opts ...grpc.CallOption) (*GetUserRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRateLimitResponse)
	err := c.cc.Invoke(ctx, RateLimitService_GetUserRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimitServiceClient) RemoveUserRateLimit(ctx context.Context, in *RemoveUserRateLimitRequest, opts ...grpc.CallOption) (*RemoveUserRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserRateLimitResponse)
	err := c.cc.Invoke(ctx, RateLimitService_RemoveUserRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimitServiceClient) GetUserSpeed(ctx context.Context, in *GetUserSpeedRequest, opts ...grpc.CallOption) (*GetUserSpeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSpeedResponse)
	err := c.cc.Invoke(ctx, RateLimitService_GetUserSpeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimitServiceClient) ListUserSpeeds(ctx context.Context, in *ListUserSpeedsRequest, opts ...grpc.CallOption) (*ListUserSpeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserSpeedsResponse)
	err := c.cc.Invoke(ctx, RateLimitService_ListUserSpeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimitServiceServer is the server API for RateLimitService service.
// All implementations must embed UnimplementedRateLimitServiceServer
// for forward compatibility.
type RateLimitServiceServer interface {
	SetUserRateLimit(context.Context, *SetUserRateLimitRequest) (*SetUserRateLimitResponse, error)
	GetUserRateLimit(context.Context, *GetUserRateLimitRequest) (*GetUserRateLimitResponse, error)
	RemoveUserRateLimit(context.Context, *RemoveUserRateLimitRequest) (*RemoveUserRateLimitResponse, error)
	GetUserSpeed(context.Context, *GetUserSpeedRequest) (*GetUserSpeedResponse, error)
	ListUserSpeeds(context.Context, *ListUserSpeedsRequest) (*ListUserSpeedsResponse, error)
	mustEmbedUnimplementedRateLimitServiceServer()
}

// UnimplementedRateLimitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimitServiceServer struct{}

func (UnimplementedRateLimitServiceServer) SetUserRateLimit(context.Context, *SetUserRateLimitRequest) (*SetUserRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserRateLimit not implemented")
}
func (UnimplementedRateLimitServiceServer) GetUserRateLimit(context.Context, *GetUserRateLimitRequest) (*GetUserRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRateLimit not implemented")
}
func (UnimplementedRateLimitServiceServer) RemoveUserRateLimit(context.Context, *RemoveUserRateLimitRequest) (*RemoveUserRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserRateLimit not implemented")
}
func (UnimplementedRateLimitServiceServer) GetUserSpeed(context.Context, *GetUserSpeedRequest) (*GetUserSpeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSpeed not implemented")
}
func (UnimplementedRateLimitServiceServer) ListUserSpeeds(context.Context, *ListUserSpeedsRequest) (*ListUserSpeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserSpeeds not implemented")
}
func (UnimplementedRateLimitServiceServer) mustEmbedUnimplementedRateLimitServiceServer() {}
func (UnimplementedRateLimitServiceServer) testEmbeddedByValue()                          {}

// UnsafeRateLimitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimitServiceServer will
// result in compilation errors.
type UnsafeRateLimitServiceServer interface {
	mustEmbedUnimplementedRateLimitServiceServer()
}

func RegisterRateLimitServiceServer(s grpc.ServiceRegistrar, srv RateLimitServiceServer) {
	// If the following call panics, it indicates UnimplementedRateLimitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimitService_ServiceDesc, srv)
}

func _RateLimitService_SetUserRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServiceServer).SetUserRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimitService_SetUserRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServiceServer).SetUserRateLimit(ctx, req.(*SetUserRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimitService_GetUserRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServiceServer).GetUserRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimitService_GetUserRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServiceServer).GetUserRateLimit(ctx, req.(*GetUserRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimitService_RemoveUserRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServiceServer).RemoveUserRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimitService_RemoveUserRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServiceServer).RemoveUserRateLimit(ctx, req.(*RemoveUserRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimitService_GetUserSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSpeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServiceServer).GetUserSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimitService_GetUserSpeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServiceServer).GetUserSpeed(ctx, req.(*GetUserSpeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimitService_ListUserSpeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserSpeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServiceServer).ListUserSpeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimitService_ListUserSpeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServiceServer).ListUserSpeeds(ctx, req.(*ListUserSpeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimitService_ServiceDesc is the grpc.ServiceDesc for RateLimitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.ratelimit.command.RateLimitService",
	HandlerType: (*RateLimitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUserRateLimit",
			Handler:    _RateLimitService_SetUserRateLimit_Handler,
		},
		{
			MethodName: "GetUserRateLimit",
			Handler:    _RateLimitService_GetUserRateLimit_Handler,
		},
		{
			MethodName: "RemoveUserRateLimit",
			Handler:    _RateLimitService_RemoveUserRateLimit_Handler,
		},
		{
			MethodName: "GetUserSpeed",
			Handler:    _RateLimitService_GetUserSpeed_Handler,
		},
		{
			MethodName: "ListUserSpeeds",
			Handler:    _RateLimitService_ListUserSpeeds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/ratelimit/command/command.proto",
}
