// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: app/ratelimit/command/command.proto

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRateLimit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EgressLimitBps  int64                  `protobuf:"varint,2,opt,name=egress_limit_bps,json=egressLimitBps,proto3" json:"egress_limit_bps,omitempty"`
	IngressLimitBps int64                  `protobuf:"varint,3,opt,name=ingress_limit_bps,json=ingressLimitBps,proto3" json:"ingress_limit_bps,omitempty"`
	EgressBps       int64                  `protobuf:"varint,4,opt,name=egress_bps,json=egressBps,proto3" json:"egress_bps,omitempty"`
	IngressBps      int64                  `protobuf:"varint,5,opt,name=ingress_bps,json=ingressBps,proto3" json:"ingress_bps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserRateLimit) Reset() {
	*x = UserRateLimit{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRateLimit) ProtoMessage() {}

func (x *UserRateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRateLimit.ProtoReflect.Descriptor instead.
func (*UserRateLimit) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *UserRateLimit) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRateLimit) GetEgressLimitBps() int64 {
	if x != nil {
		return x.EgressLimitBps
	}
	return 0
}

func (x *UserRateLimit) GetIngressLimitBps() int64 {
	if x != nil {
		return x.IngressLimitBps
	}
	return 0
}

func (x *UserRateLimit) GetEgressBps() int64 {
	if x != nil {
		return x.EgressBps
	}
	return 0
}

func (x *UserRateLimit) GetIngressBps() int64 {
	if x != nil {
		return x.IngressBps
	}
	return 0
}

type SetUserRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EgressBps     int64                  `protobuf:"varint,2,opt,name=egress_bps,json=egressBps,proto3" json:"egress_bps,omitempty"`
	IngressBps    int64                  `protobuf:"varint,3,opt,name=ingress_bps,json=ingressBps,proto3" json:"ingress_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserRateLimitRequest) Reset() {
	*x = SetUserRateLimitRequest{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserRateLimitRequest) ProtoMessage() {}

func (x *SetUserRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserRateLimitRequest.ProtoReflect.Descriptor instead.
func (*SetUserRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserRateLimitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetUserRateLimitRequest) GetEgressBps() int64 {
	if x != nil {
		return x.EgressBps
	}
	return 0
}

func (x *SetUserRateLimitRequest) GetIngressBps() int64 {
	if x != nil {
		return x.IngressBps
	}
	return 0
}

type SetUserRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserRateLimitResponse) Reset() {
	*x = SetUserRateLimitResponse{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserRateLimitResponse) ProtoMessage() {}

func (x *SetUserRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserRateLimitResponse.ProtoReflect.Descriptor instead.
func (*SetUserRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{2}
}

type GetUserRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRateLimitRequest) Reset() {
	*x = GetUserRateLimitRequest{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRateLimitRequest) ProtoMessage() {}

func (x *GetUserRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRateLimitRequest.ProtoReflect.Descriptor instead.
func (*GetUserRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRateLimitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *UserRateLimit         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRateLimitResponse) Reset() {
	*x = GetUserRateLimitResponse{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRateLimitResponse) ProtoMessage() {}

func (x *GetUserRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRateLimitResponse.ProtoReflect.Descriptor instead.
func (*GetUserRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRateLimitResponse) GetInfo() *UserRateLimit {
	if x != nil {
		return x.Info
	}
	return nil
}

type RemoveUserRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRateLimitRequest) Reset() {
	*x = RemoveUserRateLimitRequest{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRateLimitRequest) ProtoMessage() {}

func (x *RemoveUserRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRateLimitRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveUserRateLimitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveUserRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRateLimitResponse) Reset() {
	*x = RemoveUserRateLimitResponse{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRateLimitResponse) ProtoMessage() {}

func (x *RemoveUserRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRateLimitResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{6}
}

type GetUserSpeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSpeedRequest) Reset() {
	*x = GetUserSpeedRequest{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSpeedRequest) ProtoMessage() {}

func (x *GetUserSpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSpeedRequest.ProtoReflect.Descriptor instead.
func (*GetUserSpeedRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserSpeedRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserSpeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EgressBps     int64                  `protobuf:"varint,2,opt,name=egress_bps,json=egressBps,proto3" json:"egress_bps,omitempty"`
	IngressBps    int64                  `protobuf:"varint,3,opt,name=ingress_bps,json=ingressBps,proto3" json:"ingress_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSpeedResponse) Reset() {
	*x = GetUserSpeedResponse{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSpeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSpeedResponse) ProtoMessage() {}

func (x *GetUserSpeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSpeedResponse.ProtoReflect.Descriptor instead.
func (*GetUserSpeedResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserSpeedResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserSpeedResponse) GetEgressBps() int64 {
	if x != nil {
		return x.EgressBps
	}
	return 0
}

func (x *GetUserSpeedResponse) GetIngressBps() int64 {
	if x != nil {
		return x.IngressBps
	}
	return 0
}

type ListUserSpeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSpeedsRequest) Reset() {
	*x = ListUserSpeedsRequest{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSpeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSpeedsRequest) ProtoMessage() {}

func (x *ListUserSpeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSpeedsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSpeedsRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{9}
}

type ListUserSpeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*UserRateLimit       `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSpeedsResponse) Reset() {
	*x = ListUserSpeedsResponse{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSpeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSpeedsResponse) ProtoMessage() {}

func (x *ListUserSpeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSpeedsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSpeedsResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserSpeedsResponse) GetInfos() []*UserRateLimit {
	if x != nil {
		return x.Infos
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_ratelimit_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_command_command_proto_rawDescGZIP(), []int{11}
}

var File_app_ratelimit_command_command_proto protoreflect.FileDescriptor

const file_app_ratelimit_command_command_proto_rawDesc = "" +
	"\n" +
	"#app/ratelimit/command/command.proto\x12\x1axray.app.ratelimit.command\"\xbb\x01\n" +
	"\rUserRateLimit\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12(\n" +
	"\x10egress_limit_bps\x18\x02 \x01(\x03R\x0eegressLimitBps\x12*\n" +
	"\x11ingress_limit_bps\x18\x03 \x01(\x03R\x0fingressLimitBps\x12\x1d\n" +
	"\n" +
	"egress_bps\x18\x04 \x01(\x03R\tegressBps\x12\x1f\n" +
	"\vingress_bps\x18\x05 \x01(\x03R\n" +
	"ingressBps\"o\n" +
	"\x17SetUserRateLimitRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"egress_bps\x18\x02 \x01(\x03R\tegressBps\x12\x1f\n" +
	"\vingress_bps\x18\x03 \x01(\x03R\n" +
	"ingressBps\"\x1a\n" +
	"\x18SetUserRateLimitResponse\"/\n" +
	"\x17GetUserRateLimitRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"Y\n" +
	"\x18GetUserRateLimitResponse\x12=\n" +
	"\x04info\x18\x01 \x01(\v2).xray.app.ratelimit.command.UserRateLimitR\x04info\"2\n" +
	"\x1aRemoveUserRateLimitRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x1d\n" +
	"\x1bRemoveUserRateLimitResponse\"+\n" +
	"\x13GetUserSpeedRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"l\n" +
	"\x14GetUserSpeedResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"egress_bps\x18\x02 \x01(\x03R\tegressBps\x12\x1f\n" +
	"\vingress_bps\x18\x03 \x01(\x03R\n" +
	"ingressBps\"\x17\n" +
	"\x15ListUserSpeedsRequest\"Y\n" +
	"\x16ListUserSpeedsResponse\x12?\n" +
	"\x05infos\x18\x01 \x03(\v2).xray.app.ratelimit.command.UserRateLimitR\x05infos\"\b\n" +
	"\x06Config2\x8f\x05\n" +
	"\x10RateLimitService\x12\x7f\n" +
	"\x10SetUserRateLimit\x123.xray.app.ratelimit.command.SetUserRateLimitRequest\x1a4.xray.app.ratelimit.command.SetUserRateLimitResponse\"\x00\x12\x7f\n" +
	"\x10GetUserRateLimit\x123.xray.app.ratelimit.command.GetUserRateLimitRequest\x1a4.xray.app.ratelimit.command.GetUserRateLimitResponse\"\x00\x12\x88\x01\n" +
	"\x13RemoveUserRateLimit\x126.xray.app.ratelimit.command.RemoveUserRateLimitRequest\x1a7.xray.app.ratelimit.command.RemoveUserRateLimitResponse\"\x00\x12s\n" +
	"\fGetUserSpeed\x12/.xray.app.ratelimit.command.GetUserSpeedRequest\x1a0.xray.app.ratelimit.command.GetUserSpeedResponse\"\x00\x12y\n" +
	"\x0eListUserSpeeds\x121.xray.app.ratelimit.command.ListUserSpeedsRequest\x1a2.xray.app.ratelimit.command.ListUserSpeedsResponse\"\x00Bp\n" +
	"\x1ecom.xray.app.ratelimit.commandP\x01Z/github.com/xtls/xray-core/app/ratelimit/command\xaa\x02\x1aXray.App.RateLimit.Commandb\x06proto3"

var (
	file_app_ratelimit_command_command_proto_rawDescOnce sync.Once
	file_app_ratelimit_command_command_proto_rawDescData []byte
)

func file_app_ratelimit_command_command_proto_rawDescGZIP() []byte {
	file_app_ratelimit_command_command_proto_rawDescOnce.Do(func() {
		file_app_ratelimit_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_ratelimit_command_command_proto_rawDesc), len(file_app_ratelimit_command_command_proto_rawDesc)))
	})
	return file_app_ratelimit_command_command_proto_rawDescData
}

var file_app_ratelimit_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_ratelimit_command_command_proto_goTypes = []any{
	(*UserRateLimit)(nil),               // 0: xray.app.ratelimit.command.UserRateLimit
	(*SetUserRateLimitRequest)(nil),     // 1: xray.app.ratelimit.command.SetUserRateLimitRequest
	(*SetUserRateLimitResponse)(nil),    // 2: xray.app.ratelimit.command.SetUserRateLimitResponse
	(*GetUserRateLimitRequest)(nil),     // 3: xray.app.ratelimit.command.GetUserRateLimitRequest
	(*GetUserRateLimitResponse)(nil),    // 4: xray.app.ratelimit.command.GetUserRateLimitResponse
	(*RemoveUserRateLimitRequest)(nil),  // 5: xray.app.ratelimit.command.RemoveUserRateLimitRequest
	(*RemoveUserRateLimitResponse)(nil), // 6: xray.app.ratelimit.command.RemoveUserRateLimitResponse
	(*GetUserSpeedRequest)(nil),         // 7: xray.app.ratelimit.command.GetUserSpeedRequest
	(*GetUserSpeedResponse)(nil),        // 8: xray.app.ratelimit.command.GetUserSpeedResponse
	(*ListUserSpeedsRequest)(nil),       // 9: xray.app.ratelimit.command.ListUserSpeedsRequest
	(*ListUserSpeedsResponse)(nil),      // 10: xray.app.ratelimit.command.ListUserSpeedsResponse
	(*Config)(nil),                      // 11: xray.app.ratelimit.command.Config
}
var file_app_ratelimit_command_command_proto_depIdxs = []int32{
	0,  // 0: xray.app.ratelimit.command.GetUserRateLimitResponse.info:type_name -> xray.app.ratelimit.command.UserRateLimit
	0,  // 1: xray.app.ratelimit.command.ListUserSpeedsResponse.infos:type_name -> xray.app.ratelimit.command.UserRateLimit
	1,  // 2: xray.app.ratelimit.command.RateLimitService.SetUserRateLimit:input_type -> xray.app.ratelimit.command.SetUserRateLimitRequest
	3,  // 3: xray.app.ratelimit.command.RateLimitService.GetUserRateLimit:input_type -> xray.app.ratelimit.command.GetUserRateLimitRequest
	5,  // 4: xray.app.ratelimit.command.RateLimitService.RemoveUserRateLimit:input_type -> xray.app.ratelimit.command.RemoveUserRateLimitRequest
	7,  // 5: xray.app.ratelimit.command.RateLimitService.GetUserSpeed:input_type -> xray.app.ratelimit.command.GetUserSpeedRequest
	9,  // 6: xray.app.ratelimit.command.RateLimitService.ListUserSpeeds:input_type -> xray.app.ratelimit.command.ListUserSpeedsRequest
	2,  // 7: xray.app.ratelimit.command.RateLimitService.SetUserRateLimit:output_type -> xray.app.ratelimit.command.SetUserRateLimitResponse
	4,  // 8: xray.app.ratelimit.command.RateLimitService.GetUserRateLimit:output_type -> xray.app.ratelimit.command.GetUserRateLimitResponse
	6,  // 9: xray.app.ratelimit.command.RateLimitService.RemoveUserRateLimit:output_type -> xray.app.ratelimit.command.RemoveUserRateLimitResponse
	8,  // 10: xray.app.ratelimit.command.RateLimitService.GetUserSpeed:output_type -> xray.app.ratelimit.command.GetUserSpeedResponse
	10, // 11: xray.app.ratelimit.command.RateLimitService.ListUserSpeeds:output_type -> xray.app.ratelimit.command.ListUserSpeedsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_app_ratelimit_command_command_proto_init() }
func file_app_ratelimit_command_command_proto_init() {
	if File_app_ratelimit_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_ratelimit_command_command_proto_rawDesc), len(file_app_ratelimit_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_ratelimit_command_command_proto_goTypes,
		DependencyIndexes: file_app_ratelimit_command_command_proto_depIdxs,
		MessageInfos:      file_app_ratelimit_command_command_proto_msgTypes,
	}.Build()
	File_app_ratelimit_command_command_proto = out.File
	file_app_ratelimit_command_command_proto_goTypes = nil
	file_app_ratelimit_command_command_proto_depIdxs = nil
}
